name: painter
description: A simple widget to paint with your fingers. Supports setting a background color, undo and export to png!
version: 0.3.2
homepage: https://github.com/epnw/painter

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.5.1
  json_annotation: ^4.7.0
dev_dependencies:
  build_runner:

environment:
  sdk: '>=2.18.1 <3.0.0'
